---
title: "Ractification - Autocorrelation"
output: html_document
---

```{r}
#Lags, differences, autoregression
#See "Autocorrelation" file for more
#import depersonalized U.S. real GDP (FRED data); set as time series

data<-read.csv("https://raw.githubusercontent.com/hegerty/ECON343/main/USMXRY.csv",header=TRUE)
head(data)
```


```{r}
acf(data)
```
```{r}
library(tseries)
library(lmtest)
model = lm(USY~MXY, data = data)
summary(model)
```


```{r}
plot(model)
```


```{r}
dwtest = dwtest(USY~MXY,data=data)
dwtest
```
```{r}
bgtest = bgtest(USY~MXY, data = data)
bgtest
```


```{r}
usry<-ts(data[,2],start=c(1993,1),frequency = 4)
usry
lnusry<-log(usry)
lnusry
par(mfrow=c(1,2))
plot(usry)
plot(lnusry)
par(mfrow=c(1,1))

```


```{r}
#make a lag variable 
laglnusry<-lag(lnusry,-1)
laglnusry
plot(laglnusry)
```


```{r}
# Difference variable
dlnusry<-diff(lnusry)
dlnusry
plot(dlnusry)

#also make a lagged difference
lagdlnusry<-lag(dlnusry,-1)
lagdlnusry

```

```{r}
#put all four in a new datafrale
data2<-cbind(lnusry,laglnusry,dlnusry,lagdlnusry)
head(data2)
tail(data2)
```
```{r}
#remove extra observation
data2<-data2[-104,]
tail(data2)
```
```{r}
#Try regressing lnusry on its lag
reg1<-lm(data2[,1]~data2[,2])
summary(reg1)
```

```{r}
#Coefficient close to one
#BUT: Stationarity may be an issue

#Note that simply plotting residuals does not include time!
plot(reg1$residuals)
plot.ts(reg1$residuals)
```
```{r}
#Conduct Phillips-Perron stationarity test
PP.test(reg1$residuals)
#Residuals are stationary!
```

```{r}
#But individual series are not stationary
PP.test(data$USY)
PP.test(data2[,1])

```

```{r}
#Need to difference the variable
PP.test(dlnusry)
```

```{r}
#Try an autoregression on differenced lnusry
reg2<-lm(data2[,3]~data2[,4])
summary(reg2)
plot(reg2)
```
```{r}
#Can also use ar()
ar1<-ar(dlnusry,order.max = 1)
ar1

#Can also do it with arima()
arima1<-arima(dlnusry,order = c(1,0,0))
#arima1

```

```{r}
#Make a nice table
#Extract the important values
summary(reg2)[4]
#Keep t-stat for this example

#Start with a simple table--separate columns
table1<-summary(reg2)[4]
table1$coefficients[,c(1,3)]
table<-table1$coefficients[,c(1,3)]

#Add labels and round
rownames(table)<-c("Constant","DLNY(-1)")
round(table,3)

#Now concatenate and add parentheses in a new table
t1<-paste(round(table[1,1],3)," (",round(table[1,2],3),")",sep="")
t2<-paste(round(table[2,1],3)," (",round(table[2,2],3),")",sep="")

#Include R-squared
table2<-rbind(t1,t2,round(summary(reg2)$r.squared,3))
table2

#Remove quotes and add names
table2<-noquote(table2)
table2
rownames(table2)<-c("Constant","DLNY(-1)","R-sq.")
colnames(table2)<-"Coeff. (t-stat.)"

table2
```

