---
title: "scale and guides"
author: "vandana"
date: "2022-09-03"
output: html_document
---

```{r}
library(ggplot2)
p=ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ, y=hwy,color=class))
p+scale_x_continuous("Engine Displacement",breaks=c(2,4,6))+
  scale_y_continuous("MPG on Highway")+
  scale_color_discrete()
df=data.frame(x=1,y=1:4,z=1:4)
b=ggplot(data=df,aes(x,y))+geom_raster(aes(fill=z))
b
b+scale_fill_continuous(guide=guide_legend())

b+guides(fill=guide_legend(ncol=2))



```


```{r}
```


```{r}
diamonds
ggplot(data= diamonds)+
  stat_count(mapping = aes(x=cut))
ggplot(data = diamonds)+
  geom_bar(mapping=aes(x=cut,fill=color))
ggplot(data = diamonds)+
  geom_bar(mapping=aes(x=cut,fill=color))
ggplot(data = diamonds)+
  geom_bar(mapping=aes(x=cut,fill=color),position="dodge")
ggplot(data=mpg,mapping = aes(x=class,y=hwy))+
  geom_boxplot()
ggplot(data=mpg,mapping = aes(x=class,y=hwy))+
  geom_boxplot()+
  coord_flip()
ggplot(data=mpg,mapping = aes(x=class,y=hwy))+
  geom_boxplot()
ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=cut,fill=cut),width=1)+
  labs(x=NULL,y=NULL)+
  coord_polar()
```


```{r}
library(ggplot2)
splot=ggplot(mpg, aes(x=cty,y=hwy,color=factor(cyl)))+
  geom_jitter()+
  geom_abline(colour= "grey50", size=1)
splot
```


```{r}
labelled =splot+
  labs(
    x="City mileage",
    y="Highway mileage",
    colour="Cylinders",
    title="Correlation between Highway and city mileage"
  )+
  scale_color_brewer(palette="Set2")
labelled
  
```


```{r}
labelled+theme_bw()

  ```


```{r}
labelled+
  theme_bw()+
  theme(
    plot.title = element_text(face= "bold",size=20),
    legend.background = element_rect(fill = "white",size = 0.25, colour = "black"),
    legend.position = c(0.1,0.7),
    axis.ticks = element_line(colour = "grey50", size = 0.2),
    panel.grid.major = element_line(colour = "grey70", size=0.2),
    panel.grid.minor = element_blank()
  )
```


```{r}
```


```{r}
